version: "3.8"

services:
  weather_dashboard:
    build: .
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
    depends_on:
      - db
    networks:
      - app_net
    # No external port mapping here. In development, you can add a
    # docker-compose.override.yml with a port mapping (e.g., "8000:8000").

  db:
    image: postgres:15-alpine
    restart: always
    ports:
      - "127.0.0.1:5432:5432"
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - weather_db_data:/var/lib/postgresql/data
    networks:
      - app_net

networks:
  app_net:
    driver: bridge

volumes:
  weather_db_data:
