name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install --upgrade pip setuptools wheel
        pip install -r requirements.txt --retries 5 --timeout 30
        pip install flake8

    - name: Lint code with flake8
      run: |
        source venv/bin/activate
        flake8 .

    - name: Run tests with pytest
      run: |
        source venv/bin/activate
        export PYTHONPATH=.
        pytest

    - name: Build Docker image
      run: docker build -t weather_dashboard .

